#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "personal_webpages"
name = "Personal Webpages"
description.en = "Provide a static webpage for each user account"
description.fr = "Donner à chaque utilisateur un espace où construire son site statique"

version = "0.1.0~ynh1"

maintainers = ["wazdra"]

[upstream]
license = "GPL-3.0-only"
code = "https://github.com/wazdra/ynh_personal_webpages"

[integration]
yunohost = ">= 12.1.32.1"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"


disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.domain]
    # generic question handled by core
    type = "domain"

    [install.path]
    # base path where user dirs will be exposed: /people by default
    type = "path"
    default = "/people"

    [install.init_main_permission]
    # public by default
    type = "group"
    default = "visitors"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]
    # No upstream sources: this app is only Nginx configuration + system setup

    [resources.system_user]
    # Provision a unix system user for ownership of data_dir

    # No install_dir needed (nothing to deploy under /var/www)

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir
    # We'll use $data_dir/exports/<user> as bind-mount targets

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    # No custom ports, apt packages or database required for this app
