#!/bin/bash
# In simple cases, you don't need a config script.

# With a simple config_panel.toml, you can write in the app settings, in the
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

# This config script only manages the base path change via the config panel

get__base_path() {
    echo "$(ynh_app_setting_get --key=base_path)"
}

validate__base_path() {
    local p="$base_path"
    if ! echo "$p" | grep -Eq '^/[^ ]*$'; then
        echo "Invalid path"
    fi
}

set__base_path() {
    # Update setting and regenerate nginx
    ynh_app_setting_set --key=base_path --value="$base_path"
    export DATA_DIR="$data_dir"
    ynh_config_add_nginx
    ynh_systemctl --service=nginx --action=reload
}

ynh_app_config_run "$1"
